### ISSUE TITLE
Missing lib://data/data.xlsx

### ISSUE THREAD

**Issue by stefanwalther** [flautrup/SecSSE#1]
Hi,

would be nice if you could also provide the files used in the sample script (lib://data/data.xlsx).
Hard to run the example script without those files ... ;-)

Great example of how SSE can be used beyond R-integration!

Regards
Stefan

**Comment by flautrup** [comment]
The sample script is based on generated data and do not use any data files.

Regards
Fredrik

Den 18 juli 2017 00:32 skrev "Stefan Walther" <notifications@github.com>:
